services:
  - type: web
    name: galaxysonification
    env: python
    buildCommand: |
      apt-get update && apt-get install -y fluidsynth
      pip install -r requirements.txt
    startCommand: streamlit run app.py
